; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.arduino.memory_type = qio_opi
board_build.psram_type = opi
board_upload.flash_size = 8MB
board_build.partitions = default_8MB.csv
build_flags =
    -DBOARD_HAS_PSRAM
build_src_filter = +<*> -<hw_tests/>
monitor_speed = 115200
lib_deps =
    zinggjm/GxEPD2
    adafruit/Adafruit GFX Library
    adafruit/Adafruit BusIO
    earlephilhower/ESP8266Audio@1.9.9
    ricmoo/QRCode
    makuna/NeoPixelBus@^2.7.9
    bblanchon/ArduinoJson@^7.0.0

[env:settings-shifted]
extends = env:esp32-s3-devkitc-1
build_flags =
    -DBOARD_HAS_PSRAM
    -DSETTINGS_X_SHIFT=150

[env:led_strip_test]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.arduino.memory_type = qio_opi
board_build.psram_type = opi
board_upload.flash_size = 8MB
board_build.partitions = default_8MB.csv
build_flags =
    -DBOARD_HAS_PSRAM
build_src_filter = -<*> +<hw_tests/led_strip_test.cpp>
monitor_speed = 115200
lib_deps =
    makuna/NeoPixelBus@^2.7.9

[env:battery]
extends = env:esp32-s3-devkitc-1
build_flags =
    -DBOARD_HAS_PSRAM
    -DENABLE_BATTERY

[env:rtc]
extends = env:esp32-s3-devkitc-1
build_flags =
    -DBOARD_HAS_PSRAM
    -DENABLE_RTC

[env:battery-rtc]
extends = env:esp32-s3-devkitc-1
build_flags =
    -DBOARD_HAS_PSRAM
    -DENABLE_BATTERY
    -DENABLE_RTC
