#pragma once

// Generated from assets/wake_subtitles.txt by tools/gen_wake_subtitles.py.
// Edit the txt file and re-run that script to regenerate this list.

const char *const kWakeSubtitles[] PROGMEM = {
  "Today is a fresh start.",
  "Rise and shine.",
  "Make today count.",
  "One line at a time is enough.",
  "The day is yours to shape.",
  "Small steps still move you forward.",
  "A new page, still blank.",
  "You've got this.",
  "Time to get moving.",
  "Every morning is a clean slate.",
  "Let's make it a good one.",
  "The world is waiting.",
  "Coffee first, everything else after.",
  "Today won't repeat itself.",
  "Out of bed, into the day.",
  "Good things start with getting up.",
  "The sun didn't skip today either.",
  "One foot on the floor, then the other.",
  "Today has not been used yet.",
  "Let's see what happens next.",
  "A little progress is still progress.",
  "You made it to another morning.",
  "This day hasn't decided anything yet.",
  "Start small, start now.",
  "The hardest part is already done.",
  "Mornings don't have to be perfect.",
  "You don't have to feel ready to begin.",
  "Today is open for business.",
  "Whatever it is, you can handle it.",
  "Slow starts still count.",
  "The kettle won't boil itself.",
  "Stretch first, think later.",
  "Another day, another chance.",
  "This is a good moment to begin.",
  "Your bed will still be here tonight.",
  "Let the day surprise you.",
  "Nothing bad has happened yet today.",
  "The floor is right there, waiting.",
  "Getting up is the whole trick.",
  "Progress looks like this: standing up.",
  "One decision at a time.",
  "Today could go anywhere.",
  "You're allowed to start slow.",
  "The world kept turning either way.",
  "A blank calendar page, again.",
  "This morning is temporary, don't worry.",
  "Just the first step counts right now.",
  "Nobody's grading this morning.",
  "Take it one sock at a time.",
  "The day starts the moment you do.",
  "You've survived every morning so far.",
  "Consider this your gentle nudge.",
  "There's no rush, just a start.",
  "The light is on, so are you now.",
  "Today is unwritten.",
  "Let's not overthink this one.",
  "Getting vertical is step one.",
  "A new set of hours, unused.",
  "It's morning again, as promised.",
  "Nothing here requires perfection.",
  "This is just the beginning of today.",
  "You don't need a plan, just a start.",
  "The day is quiet, use it.",
  "Somewhere, coffee is being made.",
  "Today hasn't disappointed anyone yet.",
  "One deep breath, then move.",
  "The clock only moves forward.",
  "This moment is as good as any.",
  "Let today be simple.",
  "A fresh set of hours awaits.",
  "You already did the hard part: waking.",
  "Nothing's due yet, just begin.",
  "The day is still soft and quiet.",
  "Yesterday is over, this is new.",
  "Just open your eyes, the rest follows.",
  "Today is an open door.",
  "Take today one moment at a time.",
  "No greatness needed before coffee.",
  "The bed can wait, the day can't.",
  "This is the calm before the day.",
  "Let's ease into this one.",
  "A fresh 24 hours, free of charge.",
  "Nothing has gone wrong yet.",
  "Today only needs a beginning.",
  "Getting up is today's first win.",
  "The morning doesn't ask much of you.",
  "Every day starts exactly like this.",
  "Small beginnings still lead somewhere.",
  "A quiet moment before the day starts.",
  "The day hasn't judged you yet.",
  "Just show up, that's enough for now.",
  "A new morning, no instructions needed.",
  "Let today happen at its own pace.",
  "There's nothing to catch up on yet.",
  "Take the first step, the rest waits.",
  "The sun didn't wait for permission.",
  "This is simply another chance.",
  "Nothing about today is fixed yet.",
  "The morning is patient with you.",
  "One quiet step into the day.",
  "Today doesn't need to be loud.",
  "You woke up, that's the news today.",
  "A soft start is still a start.",
  "The day is a blank page again.",
  "Let's take this slow and steady.",
  "Nobody's watching this early.",
  "The first minute is the hardest part.",
  "Today is simply open.",
  "A calm morning is still a morning.",
  "You get to decide what today becomes.",
  "Nothing's happened yet, that's fine.",
  "The world moved on without complaint.",
  "Today asks only that you begin.",
  "One quiet breath before the day starts.",
  "The morning light doesn't rush you.",
  "Nothing needs solving just yet.",
  "A new day, no expectations yet.",
  "Let's see what today brings.",
  "The first step is always the smallest.",
  "This morning is yours to use.",
  "Nobody's counting how slow you start.",
  "Today is still mostly unwritten.",
  "The quiet before the day is yours.",
  "One small motion changes everything.",
  "This is where today begins.",
  "A fresh chance, no strings attached.",
  "The morning doesn't keep score.",
  "Let today unfold as it will.",
  "Nothing about now needs to be perfect.",
  "You're allowed a slow beginning.",
  "The day waits, patient as ever.",
  "Just the first movement matters now.",
  "Today hasn't asked anything of you yet.",
  "A new set of hours, still empty.",
  "The morning is simple if you let it be.",
  "One small choice starts the day.",
  "This is the easy part, just waking up.",
  "The world is quietly getting started too.",
  "Today only needs a first step.",
  "Let's begin without overthinking it.",
  "Nothing is late yet, it's still morning.",
  "A calm start beats no start.",
  "The day is still forming, take your time.",
  "You already did the hardest part.",
  "This morning has no deadlines yet.",
  "Let the day begin gently.",
  "One small motion, then the day follows.",
  "Today is simply here, nothing more.",
  "The quiet hours are still yours.",
  "A new morning, same simple rule.",
  "This is your moment before the rush.",
  "Nobody minds a slow start today.",
  "The sun is up, so is the day.",
  "Today just needs motion, not answers.",
  "A fresh page, write nothing yet.",
  "Let's ease the day open slowly.",
  "This is where things start moving again.",
  "The morning asks only for a beginning.",
  "One small step opens the whole day.",
  "Today is simply the next page.",
  "Nothing here is urgent yet.",
  "The calm before the day is still calm.",
  "A new day starts with a small motion.",
  "Let today be whatever it needs to be.",
  "This is just the start, nothing more.",
  "The world is patient this early.",
  "A quiet moment, then the day begins.",
  "Today hasn't shown its hand yet.",
  "A fresh start needs only a first step.",
  "The morning is simple, just begin.",
  "Let's not rush the first minute.",
  "Nothing's gone wrong yet today.",
  "This is the quiet edge of the day.",
  "A new morning, a simple new chance.",
  "Today only asks that you rise.",
  "The first movement is the whole trick.",
  "A soft beginning, then the day goes on.",
  "This morning is a small, open door.",
  "The day hasn't started without you.",
  "A calm beginning is still a beginning.",
  "Let today start at its own pace.",
  "Nothing needs deciding this early.",
  "Just another morning, that's enough.",
  "The quiet hours belong to you first.",
  "One small step, and the day is moving.",
  "An empty page, yours to fill today.",
  "The morning doesn't need to be rushed.",
  "A fresh chance arrives, right on time.",
  "Take today one small step at a time.",
  "A calm start before the day builds.",
  "Nobody expects much this early.",
  "The day begins the moment you do.",
  "Today is quiet, for now.",
  "The first minute is free, use it well.",
  "A new morning, no receipts required.",
  "This is the part where you just stand up.",
  "The day is empty, in a good way.",
  "One small yawn, then the day starts.",
  "Nothing needs fixing before breakfast.",
  "The morning is short on demands.",
  "This is a soft place to start from.",
  "A new day, gently delivered.",
  "Let today begin without a headline.",
  "The clock is patient, so can you be.",
  "One quiet step before the noise starts.",
  "This morning has no fine print.",
  "The day is simply waiting, not watching.",
};

// Portuguese subtitles — same purpose as kWakeSubtitles above, chosen
// from independently when the Language setting is PT (see Strings.h).
// Written accent-free: the generated fonts only contain ASCII glyphs
// (see the note in Strings.h). Not a line-by-line translation of the
// EN list — the two arrays are picked from independently at random, so
// they only need to feel right in their own language. The generator
// (tools/gen_wake_subtitles.py) should be extended to produce these
// from a per-language source file; until then this array is the
// source of truth for PT.
const char *const kWakeSubtitlesPt[] PROGMEM = {
  "Um novo dia comeca agora.",
  "Levanta-te com calma.",
  "Um passo de cada vez.",
  "O dia e teu.",
  "Cafe primeiro, o resto depois.",
  "Hoje e uma pagina em branco.",
  "Tu consegues.",
  "Hora de comecar.",
  "Cada manha e um novo comeco.",
  "Passos pequenos contam.",
  "O mundo esta a espera.",
  "Sai da cama, entra no dia.",
  "Uma decisao de cada vez.",
  "Comeca pequeno, comeca ja.",
  "Levanta-te e brilha.",
  "Respira. Depois anda.",
  "O duro ja passou: acordar.",
  "Um novo dia, uma nova chance.",
  "O dia espera por ti.",
  "Nada precisa ser perfeito.",
  "Bebe agua. Depois cafe.",
  "Um minuto de cada vez.",
  "O dia comeca contigo.",
  "Levanta-te devagar.",
  "O teu dia, as tuas regras.",
  "Segura firme, segue em frente.",
  "Manhas dificeis passam.",
  "So hoje: comeca.",
  "O corpo acordou, o resto vem.",
  "A luz acendeu-se, tu tambem.",
  "Ninguem te avalia de manha.",
  "Um dia de cada vez.",
  "Comeca pelo mais facil.",
  "Vais conseguir outra vez.",
  "Abre os olhos, o resto segue.",
  "O dia e teu para moldar.",
  "Ainda e cedo para desistir.",
  "Calma. Nao ha pressa.",
  "Um pequeno passo basta.",
  "O resto e detalhe.",
  "O dia ainda nao decidiu nada.",
  "Cafe, e o dia melhora.",
  "Ja sobreviveste a manhas piores.",
  "Vai com calma ate la.",
  "Hoje pode ser bom.",
  "O dia comeca quando te levantas.",
  "A manha pede-te so um comeco.",
  "Levanta-te uma vez, ganha o dia.",
  "Respira fundo e segue.",
  "O primeiro passo ja foi dado.",
  "Conquista a manha.",
  "Um novo conjunto de horas.",
  "Tudo comeca num pequeno gesto.",
  "Forte e quem levanta.",
  "O dia esta aberto. Usa-o.",
  "Sem pressa, sem parar.",
  "O dia e curto. Comeca bem.",
  "Manhas iniciam dias grandes.",
  "Levanta-te. O dia agradece.",
  "Um cafe afasta a duvida.",
  "Nao ha pressa, ha comeco.",
  "Levanta-te com intencao.",
  "O teu dia, do teu jeito.",
  "Passo curto, passo dado.",
  "Amanheceu. Vamos.",
  "O momento e agora.",
  "Confia: tu consegues.",
  "Comeca. O resto aparece.",
  "Nao precisas de plano, so comeco.",
  "Amanha tambem existira.",
  "Bebe agua primeiro.",
  "O tempo passa a favor de quem anda.",
  "Hoje nao se repete.",
  "Simples e comecar.",
};

constexpr int kWakeSubtitlesPtCount = sizeof(kWakeSubtitlesPt) / sizeof(kWakeSubtitlesPt[0]);

constexpr int kWakeSubtitlesCount = sizeof(kWakeSubtitles) / sizeof(kWakeSubtitles[0]);
